# Generated by Django 3.0.7 on 2020-06-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200623_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='is_merchant',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
