# Generated by Django 3.0.7 on 2020-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200624_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
