# Generated by Django 3.0.7 on 2020-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userregistration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
