# Generated by Django 3.0.7 on 2020-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200624_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
