# Generated by Django 3.0.7 on 2020-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200625_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
    ]
