# Generated by Django 3.0.7 on 2020-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200625_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Action Pending', max_length=50, null=True),
        ),
    ]
