# Generated by Django 3.0.7 on 2020-06-26 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_est_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to='shop.UserRegistration'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='shop.UserRegistration'),
        ),
    ]
