# Generated by Django 3.0.7 on 2020-06-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200626_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='house_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
