# Generated by Django 3.0.7 on 2020-06-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200628_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='lon',
        ),
    ]
