# Generated by Django 3.0.7 on 2020-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200628_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
