# Generated by Django 3.0.7 on 2020-06-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_searchmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='slots',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='wait_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
