# Generated by Django 3.0.7 on 2020-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200630_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='slots',
            field=models.CharField(default='01-01-2000', max_length=200, null=True),
        ),
    ]
