# Generated by Django 3.0.7 on 2020-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200630_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='slots',
            field=models.CharField(default='{"Date":"01-01-2000"}', max_length=1200, null=True),
        ),
    ]
